sudo: false
language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-21
    
notifications:
  email: false

android:
  components:
    - build-tools-21.1.2

before_install:
  - ls -lart
  - cd adaptive-arp-rt
  - uname -a
  
script: ./gradlew assemble build check

cache:
  directories:
  - $HOME/.gradle/wrapper/
  - $HOME/.gradle/caches/
