sudo: false
language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-21

android:
  components:
    - build-tools-22.0.1

script:
  - cd adaptive-arp-rt
  - ./gradlew build
  
cache:
  directories:
  - $HOME/.gradle/wrapper/
  - $HOME/.gradle/caches/
