sudo: false
language: android
jdk: oraclejdk8

env:
  global:
    MALLOC_ARENA_MAX=2
    
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra

script:
  - cd adaptive-arp-rt
  - ./gradlew check
